import '../styles/index.css';import {CONFIG} from './config.js';import {state} from './state.js';import {renderShell} from './ui/appShell.js';import {cameraView} from './ui/cameraView.js';import {initNotifications,notify} from './ui/notifications.js';import {bindToolbar} from './ui/toolbar.js';import {toggleSidebar} from './ui/sidebar.js';import {bindBottomSheet} from './ui/bottomSheet.js';import {bindBackgroundPanel} from './ui/backgroundPanel.js';import {renderControls} from './ui/settingsPanel.js';import {refreshGallery} from './ui/galleryPanel.js';import {openCamera,refreshDevices,switchCamera} from './camera/cameraManager.js';import {classifyDevice} from './camera/cameraDevices.js';import {createSegmentation,createFrameLoop} from './ai/segmentation.js';import {renderFrame} from './ai/renderer.js';import {capture} from './capture/capture.js';import {exportImage} from './capture/export.js';import {loadPreferences,savePreference} from './settings/preferences.js';import {isMobile} from './utils/helpers.js';
let mediaLoop;let model;let currentRecord;
const $=selector=>document.querySelector(selector);
function setPageLoading(text){cameraView.showLoading(text)}
function setupDeviceList(){const list=$('#cameraList');list.innerHTML=state.camera.devices.map((device,index)=>{const item=classifyDevice(device,index);return `<button class="cam-chip ${device.deviceId===state.camera.activeDeviceId?'active':''}" data-device="${device.deviceId}">${item.icon} ${item.name}</button>`}).join('');list.querySelectorAll('[data-device]').forEach(button=>button.addEventListener('click',()=>changeCamera(button.dataset.device)))}
async function changeCamera(id){try{setPageLoading('Cambiando cámara…');mediaLoop?.stop?.();await switchCamera(id);setupDeviceList();renderControls();mediaLoop=createFrameLoop(cameraView.video,model,processCanvas);await savePreference('deviceId',id);notify('✅ Cámara cambiada','success');cameraView.hideLoading()}catch(error){notify(`❌ No se pudo cambiar la cámara: ${error.message}`,'error');cameraView.hideLoading()}}
const processCanvas=document.createElement('canvas');processCanvas.width=CONFIG.processWidth;processCanvas.height=CONFIG.processHeight;
async function start(){renderShell($('#app'));cameraView.init();initNotifications($('#status'));state.ui.mobile=isMobile();bindBackgroundPanel();bindBottomSheet();bindToolbar({onFullscreen:()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen(),onRotate:()=>screen.orientation?.lock?.(screen.orientation.type.includes('landscape')?'portrait':'landscape').catch(()=>{}),onPanel:()=>toggleSidebar()});$('#captureBtn').addEventListener('click',takeCapture);$('#mobileCapture').addEventListener('click',takeCapture);$('#btnViewBg').addEventListener('click',()=>{state.ui.viewMode='bg';$('#btnViewBg').classList.add('active');$('#btnViewNormal').classList.remove('active')});$('#btnViewNormal').addEventListener('click',()=>{state.ui.viewMode='normal';$('#btnViewNormal').classList.add('active');$('#btnViewBg').classList.remove('active')});await refreshGallery();if(!window.isSecureContext&&location.hostname!=='localhost')throw new Error('La cámara requiere HTTPS o localhost.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('Este navegador no soporta acceso a cámara.');setPageLoading('Solicitando permiso de cámara…');const preferences=await loadPreferences();await openCamera(preferences.deviceId);cameraView.video.srcObject=state.camera.stream;await cameraView.video.play();await refreshDevices();setupDeviceList();renderControls();notify('Cargando inteligencia artificial…');model=await createSegmentation(results=>{renderFrame(cameraView.ctx,cameraView.video,results.segmentationMask);});mediaLoop=createFrameLoop(cameraView.video,model,processCanvas);$('#captureBtn').disabled=false;$('#mobileCapture').disabled=false;cameraView.hideLoading();notify('🟢 Listo. Posiciónate frente a la cámara.','success');navigator.mediaDevices.addEventListener?.('devicechange',async()=>{await refreshDevices();setupDeviceList();notify('Nueva cámara detectada','success')})}
async function takeCapture(){if(!state.camera.ready)return;try{currentRecord=await capture(cameraView.video,cameraView.canvas,state.capture.quality);await refreshGallery();cameraView.flash();notify('✅ Fotografía guardada en la galería','success');exportImage(currentRecord.edited,`ftpr-${currentRecord.id}.jpg`)}catch(error){notify(`❌ Error al guardar: ${error.message}`,'error')}}
export async function startApp(){try{await start()}catch(error){cameraView.hideLoading();notify(`❌ ${error.message}`,'error');console.error(error)}}
